# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

env:
  LINE_ACCESS_TOKEN: ${{secrets.LINE_ACCESS_TOKEN}}
  GIT_USER_NAME: ${{secrets.GIT_USER_NAME}}
  GIT_USER_EMAIL: ${{secrets.GIT_USER_EMAIL}}
  GH_PERSONAL_ACCESS_TOKEN: ${{secrets.GH_PERSONAL_ACCESS_TOKEN}}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Chrome setup
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget
        sudo apt-get install -y google-chrome-stable
    - name: Install dependencies
      run: |        
        python -m pip install --upgrade pip
        pip install chromedriver-autoinstaller
        pip install -r requirements.txt
    - name: Check installed versions
      run: |
        google-chrome --version
        chromedriver --version
    - name: Run main.py
      run: |
        python main.py
    - name: Commit changes
      run: |
        git config user.name "${GIT_USER_NAME}"
        git config user.email "${GIT_USER_EMAIL}"
        git remote set-url origin https://${GIT_USER_NAME}:${GH_PERSONAL_ACCESS_TOKEN}@github.com/junpatch/dell_price_check.git
        git remote -v
        git add .
        git commit -m "Scheduled Run"
    - name: Push changes
      run: |
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
