# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  LINE_ACCESS_TOKEN: ${{secrets.LINE_ACCESS_TOKEN}}
  LINE_USER_ID: ${{secrets.LINE_USER_ID}}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget
        sudo apt-get install -y google-chrome-stable
        
        python -m pip install --upgrade pip
        pip install chromedriver-binary==133.0.6943.126.0
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run main.py
      run: |
        python main.py
    - name: Commit changes
      run: |
        git config user.name "junpatch"
        git config user.email "junya.ishimoto@gmail.com"
        git remote set-url origin https://junpatch:${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}@github.com/junpatch/dell_price_check.git
        git remote -v
        git add .
        git commit -m "Shceduled Run"
    - name: Push changes
      run: |
        git push origin main
        
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
