# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  LINE_ACCESS_TOKEN: ${{secrets.LINE_ACCESS_TOKEN}}
  LINE_USER_ID: ${{secrets.LINE_USER_ID}}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    #- name: Lint with flake8
    # run: |
        # stop the build if there are Python syntax errors or undefined names
    #    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run main.py
      run: |
        python main.py
    - name: Commit and Push # 実行した結果をプッシュして変更をレポジトリに反映
      run: |
        git config user.name "junpatch"
        git config user.email "junya.ishimoto@gmail.com"
        git remote set-url origin https://junpatch:${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}@github.com/junpatch/dell_price_check.git
        git remote -v
        git add .
        git commit -m "Shceduled Run"
        git push origin main
